<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
	
	<div class="container">

		<h3 class="navbar-text pull-left logo">Ludicrous<i>[ly {{adjective}}]</i> Film Database</h3>
	
		<!--<h4 class="navbar-text pull-right">FAQ // Author // Source Code // Contact // The Movie DB</h4>-->

		<h4 class="navbar-text pull-right" >Powered by <img src="http://www.themoviedb.org/images/logos/tmdb-logo-1.png" height="30px"/></h4>

	</div>

</nav>
