<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	
	<div class="container">

	<form class="navbar-form">
        <div class="form-group" style="display:inline;">
            <input class="form-control input-lg" name="search" id="searchField" placeholder="Spaceballs" autocomplete="off" autofocus="autofocus" type="text" width="100%">
        </div>
      </form>

	</div>

</nav>
